# akoeb.common/tasks/main.yml
---
    # find out whether this setup has been run before
    - name: check setup status
      stat: path=/etc/ansible-setup
      register: stat

    - name: include
      include: setup.yml
      when: stat.stat.exists is not defined or not stat.stat.exists 

    - name: put a marker on the server with this setup run
      template: src=ansible-setup.j2 dest=/etc/ansible-setup owner=root group=root mode=0644
      when: stat.stat.exists is not defined or not stat.stat.exists
