# akoeb.common/tasks/main.yml
---
    # find out whether this setup has been run before
    # if the force_setup variable is set, the next task is not executed, leading to undefined stats var 
    # and forced execution of the other tasks
    - name: check setup status
      stat: path=/etc/ansible-setup
      register: setup_stat

      when: force_setup is not defined

    - name: include
      include: setup.yml
      when: setup_stat is not defined or setup_stat.stat is not defined or setup_stat.stat.exists is not defined or not setup_stat.stat.exists 

    - name: put a marker on the server with this setup run
      template: src=ansible-setup.j2 dest=/etc/ansible-setup owner=root group=root mode=0644
      when: setup_stat is not defined or setup_stat.stat is not defined or setup_stat.stat.exists is not defined or not setup_stat.stat.exists
