# akoeb.common/tasks/main.yml
---
    # initial dist upgrade, fail2ban
    - name: Run apt dist upgrade
      apt: upgrade=dist update_cache=yes 

    - name: Install various packages
      apt: 
        name: "{{item}}"
        state: installed
      with_items: 
        - sudo
        - fail2ban
        - unattended-upgrades
        - ufw
        - logwatch
        - nullmailer
        - ntp
        - collectd
        - collectd-utils
    
    # user access
    - name: Make sure the auto user is installed, but cannot login (login only with key)
      user: name={{username}} uid=2000 append=yes groups=sudo password="!" shell="/bin/bash"
    
    - name: make sure the auto user has the ssh key it needs
      authorized_key: 
        user: "{{username}}"
        key: "{{ lookup('file', 'auto.pub') }}" 
        manage_dir: yes 
        state: present 
    
    - name: Disallow password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: Restart sshd
    
    - name: Allow ssh access only to auto and vagrant user
      lineinfile: 
        dest: /etc/ssh/sshd_config 
        regexp: "^AllowUsers" 
        line: "AllowUsers {{ssh_allow_users}}"
        state: present
      notify: Restart sshd
    
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config regexp="PermitRootLogin\s+" line="PermitRootLogin no" state=present
      notify: Restart sshd
    
    - name: Remove sudo group rights
      lineinfile: dest=/etc/sudoers regexp='^%sudo' state=absent

    - name: make sure the sudoers file allows the group sudo without password prompt
      lineinfile: dest='/etc/sudoers' regexp='^{{username}}' line='auto ALL=(ALL) NOPASSWD:ALL' state='present'

    - name: deactivate root password
      user: name=root password="!"
    
    
    # unattended upgrades
    - name: Adjust APT update intervals
      copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic
    
    - name: configure mailing in unattended upgrades
      lineinfile:
          dest: /etc/apt/apt.conf.d/50unattended-upgrades
          regexp: "Unattended-Upgrade::Mail "
          line: 'Unattended-Upgrade::Mail "{{admin_email}}";'
    
    # logwatch
    - name: Make logwatch mail to admin_email daily
      lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{admin_email}} --detail high" state=present create=yes
    
    
    # firewall:
    - name: configure firewall to allow ssh incoming from /etc/ufw/applications.d/openssh-server
      ufw: rule=allow name=OpenSSH state=enabled 
    
    - name: default outgoing firewall policy (drop)
      lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_OUTPUT_POLICY=" line="DEFAULT_OUTPUT_POLICY=DROP" state=present
    
    - name: allow DNS lookups
      ufw: rule="allow" name="DNS" direction=out state=enabled
    
    - name: allow outgoing http traffic for getting system updates
      ufw: rule=allow name="WWW Full" direction=out  state=enabled

    - name: allow outgoing dhcp requests
      ufw: rule=allow proto=udp to_ip=109.239.48.251 to_port=67 direction=out state=enabled
    
    - name: allow ntp traffic outbound
      ufw: rule=allow port=123 proto=udp direction=out state=enabled

    - name: allow mail submission to mail relay server
      ufw: rule=allow to_ip={{relay_host_ip}} name="Mail submission" direction=out state=enabled


    # nullmailer 
    - name: configure nullmailer adminaddress
      copy: content="{{admin_email}}\n" dest=/etc/nullmailer/adminaddr
      notify: Restart nullmailer

    - name: configure nullmailer mailname
      copy: content="{{hostname}}\n" dest=/etc/mailname
      notify: Restart nullmailer

    - name: configure nullmailer defauldomain
      copy: content="{{defaultdomain}}\n" dest=/etc/nullmailer/defaultdomain
      notify: Restart nullmailer

    - name: configure nullmailer relayhost
      copy: dest=/etc/nullmailer/remotes content="{{relay_host}} smtp --port=587 --user={{relay_user}} --pass={{relay_passwd}} --starttls --insecure\n"
      notify: Restart nullmailer

      # collectd
    - name: upload collectd config
      copy: src=collectd.conf dest=/etc/collectd/collectd.conf owner=root group=root mode=0644 backup=yes
      notify: Restart collectd
     
    - name: create directory for other collectd configs which can be put there later
      file: path=/etc/collectd/others state=directory owner=root group=root mode=0750 
      notify: Restart collectd
      

    # TODO: install ossec

