admin_email: admin@example.com
defaultdomain: example.com
hostname: host1.example.com
relay_host: mail.example.com
relay_host_ip: 192.168.1.1/32
relay_user: RELAY_USER
relay_passwd: SMTP_PASSWORD
username: "deploy"
ufw_log_level: "low"

